name: Build and Release Multi-Platform Binaries

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=logo.ico --name=SpotAFan --add-data="logo.ico:." --add-data="spotafan/ui/lang.json:spotafan/ui" --hidden-import=PySide6.QtMultimedia --hidden-import=mutagen --hidden-import=yt_dlp --hidden-import=requests --hidden-import=datetime main
        
    # Creates or overwrites the rolling "latest" release with the binaries
    - name: Install NFPM and Pack Arch Linux Package
      if: matrix.os == 'ubuntu-latest'
      run: |
          # Add the goreleaser repo to the standard sources.list.d directory
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          
          # Update packages and install nfpm
          sudo apt-get update && sudo apt-get install nfpm -y
          
          # Build the Arch package
          nfpm package --config nfpm.yaml --packager archlinux --target dist/
